#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t broken-links:nil c:nil creator:t
#+OPTIONS: date:nil e:t email:t f:t inline:t num:t
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:nil tasks:t tex:t
#+OPTIONS: timestamp:t title:t toc:t todo:t |:t
#+TITLE: Registro de Actividades
#+DATE: <2018-06-11 Mon>
#+AUTHOR: Abel Güitian
#+EMAIL: aang.drummer@gmail.com
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 25.3.2 (Org mode 9.1.3)
#+SETUPFILE: theme-readtheorg.setup

* Introducción

Este documento es creado con la finalidad de registrar las actividades que estaré realizando
dentro del lapso de tiempo de mi servicio social, en la facultad de ingeniería mecánica y eléctrica, en la Universidad Autónoma de Nuevo León.
Se tienen que cumplir con un tiempo determinado, esto más específicamente hablando es hacer un total de 80 horas mensuales, lo que equivale 
a un total de 4 horas por día de lunes a viernes.

El formato o manera de construir este archivo es el siguiente:
- Dentro del apartado de /Actividades/ habrán sub-apartados o sub-títulos que tendrán comúnmente la fecha en la que se realizó la actividad con
  formato /<Año-mes-día indicio del día>/ (Por ejemplo: <2018-03-19 Mon> /Esto es lunes marzo 19 del 2018/).
- También los subtítulos podrían presentarse a manera de múltiples fechas o sesiones, ya que podría estar trabajando en un mismo tema en específico.
- Este archivo cuenta con un :LOGBOOK: dónde se buscará plasmar el tiempo invertido en cada sesión de trabajo.
- El hecho de que no exista una serie consecutiva de días no quiere decir, que no se trabajo en los días no escritos en el apartado de actividades, si no que
  se estuvo trabajando en el mismo tema, y los tiempos empleados pueden encontrarse en la tabla de tiempos general.
- También se incluye un apartado de /footnotes/, en ella se encuentran referencias a conceptos, que yo en lo particular no sabía o no tengo claro
  o sólo por el simple hecho de llevar retroalimentación en la documentación.
  
:LOGBOOK:
CLOCK: [2018-06-16 Sat 14:34]--[2018-06-16 Sat 20:25] =>  5:51
Se actualizara la interacción para informar de como estaré llevando a cabo el registro de actividades.
:END:


* Actividades

** <2018-06-11 Mon>
Debido a mi semana de exámenes y problemas de salud, empecé el servicio social prácticamente una semana después.
Por lo que este día me puse de acuerdo con la /Dra. Elisa Schaeffer/ acerca de lo que voy a realizar en el servicio social.
Me comento ciertas opciones acerca de los temas en los que podría estar trabajando. Al final tenía que elegir solamente una opción.
El tema que escogí tiene que ver con la epidemiología[fn:1], más concretamente en la predicción de epidemias usando herramientas como la 
probabilidad y estadística, matemáticas discretas, inteligencia artificial y otras más.

De igual manera creé un repositorio en [[https://sourceforge.net/][sourcefourge.net]] donde almacenaré los avances obtenidos y el registro de actividades que tú estás leyendo en este momento.

- Note taken on [2018-06-19 Tue 15:01] \\
  El repositorio fue migrado a github debido a problemas con SourceForge. Nuevo enlace: [[https://github.com/aang7/sservice]]


** <2018-06-12 Tue>
:LOGBOOK:
CLOCK: [2018-06-12 Tue 12:02]--[2018-06-12 Tue 16:35] =>  4:33
:END:

Para poder llevar a cabo este documento tuve que investigar un poco acerca de /[[https://orgmode.org/][org-mode]]/. Org mode es un _modo_ o _paquete_ en /emacs/ que ayuda en el mantenimiento
de notas, /To-Do lists/, planificación de proyectos, etc. He realizado pequeñas documentaciones con esta herramienta que considero muy flexible, aunque
un poco difícil de aprender en mi opinión. La documentación se realiza en texto plano con el formato de org-mode, pero org-mode tiene la opción 
de exportar el texto a otro formato, por ejemplo, un pdf, html, etc. Estos son algunos de los enlaces/tutoriales que me sirvieron para tener la oportunidad
de usar emacs para la realización de esta documentación.

- [[https://www.youtube.com/watch?v=iYkuzV3Pu68&t=304s][Emacs for note-taking / outlining]]
- [[https://www.youtube.com/watch?v=SzA2YODtgK4][Getting Started With Org Mode]]
- [[https://www.youtube.com/watch?v=dljNabciEGg&t=1427s][Literate Devops with Emacs]]

** <2018-06-13 Wed>
Empezando a refrescar y adquirir conocimientos de probabilidad y estadística. El [[https://www.amazon.com/Probability-Statistics-Engineering-Sciences-Devore/dp/0538733527][libro]] que estoy utilizando:
#+BEGIN_VERSE
Probability and Statistics for Engineering and the Sciences (Eighth Edition)
-Jay Devore
#+END_VERSE

Las anotaciones, se pueden ver en el apartado de [[#pye:one][Anotaciones]]. Dentro de cada punto se anotan tiempos empleados y se muestran en el archivo /.org/.

** <2018-06-18 Mon>
:LOGBOOK:
CLOCK: [2018-06-24 Sun 12:50]--[2018-06-24 Sun 16:10] =>  3:20

:END:

Estuve teniendo problemas para organizar dentro de SourceForge la manera de poder administrar un alojamiento web (web hosting), tarde un tiempo razonable solamente
tratando de encontrar la manera en la que quería mostrar este archivo (página web estática). Al final encontré la manera pero, por alguna extraña razón ya no pude acceder a mi cuenta, 
me frustre y opté por alojar todo en /github/.
Tengo un repositorio llamado [[https://github.com/aang7/sservice][sservice]], existe una /branch/ llamada /gh-pages/, dentro de ella, estará actualizándose este archivo, tanto el /.org/ como el /html/.


** TODO <2018-06-19 Tue>
:LOGBOOK:
CLOCK: [2018-06-19 Tue 13:49]--[2018-06-19 Tue 17:49] =>  4:00
:END:

- Note taken on [2018-06-25 Mon 09:45] \\
  Aún falta integrar la evidencia de esto.

Realizando ejercicios del material [[https://elisa.dyndns-web.com/teaching/prob/prob.html][en línea]] proporcionado por mi tutora.  Estos se encuentran en la rama de trabajo /master/, dentro del repositorio /sservice/.
** <2018-06-20 Wed>
Estuve tratando de importar datos de tablas en un pdf, los datos son referidos a datos epidemiológicos.
La manera en que trate fue, el pasar el pdf a imágenes y analizar mediante visión computacional para poder obtener la información.
#+BEGIN_SRC c++


  #include <iostream>
  #include <opencv2/opencv.hpp>

  using namespace std;
  using namespace cv;



  int main()
  {
      // Load source image
      string filename = "sem21-15.jpg";
      Mat src = imread(filename);

      // Check if image is loaded fine
      if(!src.data) {
          cout << "Problem loading image!" << endl;
          return -1;
      }

      // show the original image
      namedWindow("original", WINDOW_NORMAL);
      imshow("original", src);

      //Transform source image to gray if it is not
      Mat gray;

      if (src.channels() == 3)
          cvtColor(src, gray, CV_BGR2GRAY);

      else
          gray = src;


       // Apply adaptiveThreshold at the bitwise_not of gray, notice the ~ symbol
      Mat bw;
      adaptiveThreshold(~gray, bw, 255, CV_ADAPTIVE_THRESH_MEAN_C, THRESH_BINARY, 15, -2);

      // Show binary image
      namedWindow("binary", WINDOW_NORMAL);
      imshow("binary", bw);


      // Create the images that will use to extract the horizonta and vertical lines
      Mat horizontal = bw.clone();
      Mat vertical = bw.clone();


          int scale = 15; // play with this variable in order to increase/decrease the amount of lines to be detected

      // Specify size on horizontal axis
      int horizontalsize = horizontal.cols / scale;

      // Create structure element for extracting horizontal lines through morphology operations
      Mat horizontalStructure = getStructuringElement(MORPH_RECT, Size(horizontalsize,1));

          // Apply morphology operations
      erode(horizontal, horizontal, horizontalStructure, Point(-1, -1));
      dilate(horizontal, horizontal, horizontalStructure, Point(-1, -1));
      //    dilate(horizontal, horizontal, horizontalStructure, Point(-1, -1)); // expand horizontal lines

      // Show extracted horizontal lines
      namedWindow("horizontal", WINDOW_NORMAL);
      imshow("horizontal", horizontal);


      waitKey(0);
      return 0;
  }

#+END_SRC

Realmente el código principal es la idea de otra persona, solo estuve tratando de tomar recursos de esa idea, pero al final me di cuenta que no iba a seguir en esto,
por el momento.


** TODO <2018-06-21 Thu>
:LOGBOOK:
CLOCK: [2018-06-21 Thu 13:50]--[2018-06-21 Thu 17:50] =>  4:00
:END:
Investigando dentro de un libro llamado /[[https://www.amazon.com/Probability-Decisions-Games-Gentle-Introduction/dp/1119302609][Probability, Decisions and Games]]/. A diferencia del libro de Devore, contiene ejercicios en R

 
* Anotaciones

Dentro de este apartado, se plasma información que decido anotar, para dar seguimiento a la investigación y aprendizaje que estoy realizando.
Es demasiada la información que puedo leer en un par de días por lo que creo que, es importante que haga mis anotaciones y no sólo
que registre lo que he estado haciendo de manera general, pero si de manera un poco más específica.

** Devore -  Probabilidad y Estadística 

*** TODO Capítulo 1
:PROPERTIES:
:CUSTOM_ID: pye:one
:END:
:LOGBOOK:
CLOCK: [2018-06-15 Fri 14:35]--[2018-06-15 Fri 18:36] =>  4:01
CLOCK: [2018-06-14 Thu 14:56]--[2018-06-14 Thu 19:33] =>  4:37

:END:

*Población*: Una investigación típicamente se enfocara en una colección de objetos bien definida, constituyendo una población de interés. \\
*Muestra*: Subconjunto de una población.

Dentro de una población usualmente estamos interesados sólo en ciertas características, por ejemplo, la edad de una persona, el género de un graduado
en ingeniería, etc.

Una _variable_ es cualquier característica que su valor puede cambiar de un objeto a otro dentro de la población. Una _característica_ puede ser categórica o numérica.
El género (femenino o masculino) es una variable categórica.

**** Ramas de la estadística
Es posible que un investigador que ha recopilado datos desee resumir y describir características 
importantes de los mismos. Esto implica utilizar métodos de *estadística descriptiva*.
Algunos de ellos son de naturaleza gráfica; la construcción de histogramas, diagramas de
caja y gráficas de puntos son ejemplos primordiales. Otros métodos descriptivos implican el cálculo 
de medidas numéricas, tales como medias, desviaciones estándar y coeficientes de correlación.

Después de haber obtenido una muestra de una población, un investigador con frecuencia desearía utilizar 
la información muestral para sacar algún tipo de conclusión (hacer una inferencia de alguna clase) con respecto
 a la población. Es decir, la muestra es un medio para llegar a un fin en lugar de un fin por sí misma. _Las técnicas para generalizar desde 
una muestra hasta una población se congregan dentro de la rama de la disciplina llamada *estadística inferencial*_.

**** Estudios Enumerativos vs Analíticos

*Estudio enumerativo*: el interés se enfoca en un conjunto de individuos u objetos finito, identificable y no cambiante que
conforman una población. Un marco de muestreo, es decir, una lista de los individuos u objetos que tienen que ser muestreados, está disponible para un investigador o puede ser construida. 
Por ejemplo, el marco puede contener números de serie de todos los hornos fabricados por una compañía particular durante cierto periodo; se puede
seleccionar una muestra para inferir algo sobre la duración promedio de estas unidades. \\
*Estudio analítico*: se define ampliamente como uno que no es de naturaleza enumerativa. Tales estudios a menudo se realizan con el objetivo de mejorar un producto futuro al
actuar sobre un proceso de una cierta clase (p. ej., recalibrar equipo o ajustar el nivel de alguna
 sustancia tal como la cantidad de un catalizador). A menudo se obtienen datos sólo 
sobre un proceso existente, uno que puede diferir en aspectos importantes del proceso futuro. 
No existe por lo tanto un marco de muestreo que enliste los individuos u objetos de interés. Por ejemplo, una muestra de cinco turbinas con un nuevo diseño puede ser fabricada
y probada para investigar su eficiencia. 

**** Recopilación de datos
La estadística se ocupa no sólo de la organización y análisis de datos una vez que han sido
recopilados sino también con el desarrollo de técnicas de recopilación de datos. Si éstos no
son apropiadamente recopilados, un investigador no puede ser capaz de responder las preguntas
consideradas con un razonable grado de confianza.

** TODO R stuff

- Note taken on [2018-06-21 Thu 09:53] \\
  Aún falta incluir varias cosas.
*** Leyendo Archivos desde R
:LOGBOOK:
CLOCK: [2018-06-22 Fri 16:13]--[2018-06-22 Fri 20:14] =>  4:01
:END:

Para poder analizar datos en R es necesario "importar" esos "datos". Hay múltiples maneras de leer un archivo y hay múltiples contenedores de datos, por ejemplo podemos leer datos desde un archivo flat (.csv, .txt, etc), 
desde una base de datos, desde un excel, etc.
R nos facilita mucho la vida por que cuenta con paquetes cargados de manera predeterminada al iniciar /R/ que contienen funciones útiles para poder cargar datos dependiendo el contenedor o la fuente (archivo, base de datos, etc.).
Como ejemplo abriremos un archivo llamado /hotdogs.txt/ y mostraremos la estructura de los datos.

#+NAME: hotdogs.txt
#+BEGIN_VERSE
Beef	186	495
Beef	131	317
Beef	149	319
Beef	135	298
Beef	132	253
Meat	153	372
Meat	107	144
Meat	195	511
Meat	135	405
Meat	140	428
Meat	138	339
Poultry	142	513
Poultry	86	358
Poultry	143	581
Poultry	152	588
Poultry	146	522
Poultry	144	545

#+END_VERSE


#+BEGIN_SRC R :exports both :results output
    # Path to the hotdogs.txt file: path
    path <- file.path("./", "hotdogs.txt")

    # Import the hotdogs.txt
    hotdogs <- read.table(path, 
                          sep = "\t", 
                          col.names = c("type", "calories", "sodium"))

    # Call head() on hotdogs
    str(hotdogs)


  # Reading a csv file
  pools <- read.csv("swimming_pools.csv", stringsAsFactors=FALSE)

  str(pools)


#+END_SRC

#+RESULTS:
: 'data.frame':	17 obs. of  3 variables:
:  $ type    : Factor w/ 3 levels "Beef","Meat",..: 1 1 1 1 1 2 2 2 2 2 ...
:  $ calories: int  186 131 149 135 132 153 107 195 135 140 ...
:  $ sodium  : int  495 317 319 298 253 372 144 511 405 428 ...
:
: 'data.frame':	8 obs. of  4 variables:
:  $ Name     : chr  "Acacia Ridge Leisure Centre" "Bellbowrie Pool" "Carole Park" "Centenary Pool (inner City)" ...
:  $ Address  : chr  "1391 Beaudesert Road, Acacia Ridge" "Sugarwood Street, Bellbowrie" "Cnr Boundary Road and Waterford Road Wacol" "400 Gregory Terrace, Spring Hill" ...
:  $ Latitude : num  -27.6 -27.6 -27.6 -27.5 -27.4 ...
:  $ Longitude: num  153 153 153 153 153 ...


Esto es sólo un ejemplo básico, pero la verdad es que muchas veces el leer datos es más complicado que esto, por que se tienen que leer cantidades muy grandes de información y la información muchas veces se tiene que conseguir, 
o viene muy "sucia".



* Tabla de tiempos 
#+BEGIN: clocktable :maxlevel 2 :scope file
#+CAPTION: Clock summary at [2018-06-25 Mon 09:56]
| Headline                                 |       Time |      |
|------------------------------------------+------------+------|
| *Total time*                             | *1d 10:23* |      |
|------------------------------------------+------------+------|
| Introducción                             |       5:51 |      |
| Actividades                              |      15:53 |      |
| \_  <2018-06-12 Tue>                     |            | 4:33 |
| \_  <2018-06-18 Mon>                     |            | 3:20 |
| \_  <2018-06-19 Tue>                     |            | 4:00 |
| \_  <2018-06-21 Thu>                     |            | 4:00 |
| Anotaciones                              |      12:39 |      |
| \_  Devore -  Probabilidad y Estadística |            | 8:38 |
| \_  R stuff                              |            | 4:01 |
#+END:

* Footnotes

[fn:1] Parte de la medicina que estudia el desarrollo epidémico y la incidencia de las enfermedades infecciosas en la población.
