* Clean aspects to consider

- Quitar comas si es que son el ultimo caracter en la línea [IMPORTANT: TODO]
- Quitar líneas que contengan regex como: entidad, federativa, CIE, etc.
- Identificar las líneas que contengan los años e.g. 2015, 2016, etc.
  - Esto es super importante por que asi puedo determinar que va con que

- Note taken on [2018-07-17 Tue 10:10] \\
  Al parecer el script no hace su jale como debe.

- Note taken on [2018-07-19 Thu 19:45] \\
  Necesito eliminar las comas al final de la línea, están solas, son inútiles, también necesito eliminar comas dentro de
  doble commillas.

- Note taken on [2018-07-21 Sat 15:03] \\
  Me tope con que no todas las tablas cumple con el patrón (numero de nombres de enfermedades*4 == cantidad de columnas de datos) [Esto sin tomar en cuenta el primer elemento]. Entonces necesito ver como puedo arreglar eso...

- Note taken on [2018-08-21 Tue 15:28] \\
  Ahora puedo realmente filtrar los archivos en los que algo anda mal, Les llamo _Anomaly Files_.

- Note taken on [2018-09-02 Sun 21:06] \\
  Tengo algunos TODO and WARNINGS comments en myscript.sh.
  Detalles que pueden ser relevantes. Al día van 3. #INVERSION: Desde las 7 hasta las 10

- Note taken on [2018-09-09 Sun 23:35] \\
  Inversion desde las 8 hasta las 12.
  Comitie mi avance. Ya hice el ejemplo de extracción de datos de cierta enfermedad, faltan detalles. Pero me estoy acercando.
Lo que se me ocurre para generar los archivos csv por enfermedades, es ir buscando por nombre.
Esto podría solucionarse con un grep recursivo.
Escribire los pasos que se me ocurren podría hacer para solucionar este problema.


Lo que haré será crear un ejemplo de la funcionalidad que quiero, me refiero al siguiente
algoritmo:
#+BEGIN_CENTER
- Hacer grep recursivo dando solamente como patrón el nombre de la enfermedad.
- Recorrer los archivos en los que se encontró.
- Identificar la columna en la que esta y extraer sus datos.
- Es necesario tener la semana a la que pertenece y por supuesto el año(Que podemos tomarlos desde el nombre del file)
#+END_CENTER

#+NAME: Caracteristicas
Creare archivos por enfermedad por año, con el siguiente formato:

Año
Semp.ep,1,,,2,,,3
E.F, SemCASOS, H Ac., M Ac.,  
Agu
BCN

Primero lo que haré será un ejemplo de extracción de datos de cierta enfermedad.
Para ello usare el siguiente algoritmo:
#+BEGIN_CENTER
- Ubicar la columna de la enfermedad (DONE)
- obtener las lineas de interes(las de los datos)
- 
#+END_CENTER

#+NAME: Using functions by reference: sample
#+BEGIN_SRC bash

  # The first arg has to be the array and the second the element to add 
  function addToArray() {
      local -n a1=$1
      a1=(${a1[@]} $2) # save it
  }

  miarray=()
  addToArray miarray "Hola"
  echo ${miarray[@]}




# this may help i just need to process every file
sed -i 's/,[[:blank:]]*$//g' *.csv > tmp.tmp # https://unix.stackexchange.com/questions/220576/how-to-remove-last-comma-of-each-line-on-csv-using-linux

#+END_SRC


Estuve tratando de separar algunas funciones que creo podrían servir despues 

#+BEGIN_SRC bash

    #command="/${years[0]},/ || /${years[1]}/ {print FNR}" # in general each csv has only two different years


      . ./utils.lib
      a="2015,esto,es,107,prueba"
      b=','
      marray=();
      SplitLineByDelimeter a b ga;
      echo "${ga[@]}"
      GetNumericalValues ga
      echo "${ga[@]}"


  :'
    Delete commas at the end of the lines and between double quotes.
    This function use global variables to work with
  '
  function DeleteCommas() {
      FILE_EXTENSION=".csv"
      DIR="newProgram"
      files="$DIR/*$FILE_EXTENSION";
      echo $files
      for file in $files; do
          sed -i -e':a;s/^\(\([^"]*,\?\|"[^",]*",\?\)*"[^",]*\),/\1 /;ta' -e 's/,[[:blank:]]*$//g' $file
      done
  }

#+END_SRC



* References

- https://stackoverflow.com/questions/918886/how-do-i-split-a-string-on-a-delimiter-in-bash
- https://stackoverflow.com/questions/5385234/using-sed-awk-to-print-lines-with-matching-pattern-or-another-matching-pattern
- https://stackoverflow.com/questions/16529716/awk-save-modifications-in-place
- https://stackoverflow.com/questions/6958841/use-grep-to-report-back-only-line-numbers
- https://stackoverflow.com/questions/17533231/how-can-i-delete-an-element-in-an-array-and-then-shift-the-array-in-shell-script
- https://stackoverflow.com/questions/45796762/concat-array-elements-with-comma-and-single-quote-bash
- https://stackoverflow.com/questions/14511295/bash-integer-comparison
- https://stackoverflow.com/questions/6022384/bash-tool-to-get-nth-line-from-a-file
- https://stackoverflow.com/questions/7248031/meaning-of-in-shell-scripts
- https://stackoverflow.com/questions/19417015/how-to-copy-an-array-in-bash
- https://stackoverflow.com/questions/18568706/check-number-of-arguments-passed-to-a-bash-script
- https://stackoverflow.com/questions/11145270/how-to-replace-an-entire-line-in-a-text-file-by-line-number/11145362
- https://stackoverflow.com/questions/18266348/how-to-only-get-the-number-of-lines-of-a-file
- https://stackoverflow.com/questions/25947072/how-to-check-that-a-file-has-more-than-1-line-in-a-bash-conditional
- https://unix.stackexchange.com/questions/220576/how-to-remove-last-comma-of-each-line-on-csv-using-linux
- https://www.shellscript.sh/functions.html
  
